# Stage 1: Build the Go application
FROM golang:1.19 AS builder

WORKDIR /usr/src/app

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY . .

COPY .env .

# RUN go build -o /usr/src/app/main .

RUN go build -o serverexec ./main.go

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=${DB_USER}
ENV POSTGRES_PASSWORD=${DB_PASSWORD}
ENV POSTGRES_DB=${DB_NAME}

# Expose ports
EXPOSE 3000

ENTRYPOINT [ "/usr/src/app/serverexec" ]

# CMD [""]